language: python
python:
  - 2.7
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - virtualenv .
  - bin/pip install --upgrade pip setuptools zc.buildout
install:
  - pip install -q docutils  # for setup.py check -r -s
  - bin/buildout -Nc travis.cfg
script:
  - bin/check-manifest
  - python setup.py check -r -s
  - bin/code-analysis
  - bin/dependencychecker
  - bin/test
  - bin/createcoverage

after_success:
  - pip install -q coveralls
  - coveralls

notifications:
  email:
    - gilforcada@gmail.com
