name: Linting
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  test:
    name: Linting on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('requirements-lint.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-
      - name: pip version
        run: pip --version
      - name: Install dependencies
        if: matrix.python-version == '3.8'
        run: python -m pip install -r requirements-lint.txt
      # formatters
      - name: Run pyupgrade
        run: pyupgrade --py37-plus *.py
      - name: Run isort
        run: isort --check-only *.py
      - name: Run black
        run: black --check --skip-string-normalization *.py
      # linters
      - name: Lint with flake8
        run: flake8 *.py --count --show-source --statistics

